### ISSUE TITLE
Define class labels of interest for models

### ISSUE THREAD

**Issue by tjiagoM** [CEPrE-Unilurio/underwater_od#2] opened 2020-10-01 09:08 UTC
We will need to define a basic set of class labels for our initial POC. I will talk with Erwan to define it better.

I'm adding this both to "Dataset handling" and "basic pre-trained model ..." projects because this will influence how we join different datasets as well as how we edit models in the future.

**Comment by tjiagoM** [comment] 2020-11-06 19:39
Erwan defined the following labels to start (folder shared privately):

0. Anthia
1. Angelfish
2. Barracudas
3. Batfish
4. Boxfish
5. Butterflyfish
6. Crabs
7. Dameselfish
8. Emperorfish
9. Fusiliers
10. goatfish
11. Gobies
12. Groupers
13. Hawkfish
14. Kingfish
15. Lionfish
16. Lobsters
17. Morray-eels
18. Nudibranches
19. Parrotfish
20. Pipefish
21. Pufferfish
22. Rays
23. Scorpionfish
24. Sharks
25. Shrimps
26. Snails
27. Snappers
28. Squirrelfish
29. Surgeonfish
30. Sweetlips
31. Triggerfish
32. Trumpetfish
33. Wrasses

**Comment by nlauchande** [comment] 2021-01-18 06:22
Chores: Marking this as closed as the issue is done.

**Closed as completed by nlauchande** 2021-01-18 06:22 UTC
